### ISSUE TITLE
[R&D] Add LoadBalancer for vl3 networks

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/deployments-k8s#9210]
## Overview

NSM vl3 could be perceived as alternative of k8s networks. Currently, k8s service is most useful thing in k8s network. 

At this moment, NSM vl3 netowk doesn't provide any alternative of k8s services. So we need to consider and implement the best solution for it.

## TODO

- [ ] Suggest options for implementation ~9h
- [ ] Get approve from Ed
- [ ] Implement the solution
- [ ] Add tests and examples
- [ ] Pass CI

## Initial ideas

1.  Modify current DNS system for vl3 networks and implement DNS loadbalancing for DNS chain.
2. Implemenet seprate vl3 component for loadbalacing.

**Comment by NikitaSkrynnik** [comment]
There are a few options for l7 load balancing:

### Option 1

We can use existing load balancers (NGINX for example). Load Balancer somehow need to know about our workloads on vl3 network and group them

### Option 2

We can do DNS load balancing. It requires some additional chain elements for vl3 dns servers and chain elements for grouping workloads

### Options 3

We can create our own load balancer as a separate component. It should scan all workloads in vl3 network, group them and assign dns name or ip address for each of the groups

**Comment by NikitaSkrynnik** [comment]
### Decomposition
1. Suggest options for implementation - 7h
2. Get approve from Ed - 10h
3. Implement the solution - 27h
3.1. Create a separate component for Load Balancer - 20h
3.2. Test this component - 7h
3.3. ...
4. Add example to deployments-k8s - 14h
5. Pass CI - 7h

**Comment by glazychev-art** [comment]
@edwarnicke 
We have prepared a doc for this feature:
https://docs.google.com/document/d/10oA0kPvlGdQP61-BgjIL6YTk8lTakyR1mce4oFYijYQ

**Comment by glazychev-art** [comment]
vL3 Load Balancer example is a part of feature tests - https://github.com/networkservicemesh/deployments-k8s/tree/v1.11.0-rc.1/examples/features/vl3-lb
